sudo: required
services:
  - docker

before_install:
  - docker build -t kc/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kc/docker-react npm run test -- --coverage

language: generic

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-461786652593"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_eky: 
    secure: $AWS_SECRET_KEY
