sudo: required
services:
  - docker

before_install:
  - docker build -t kc/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kc/docker-react npm run test -- --coverage

language: generic    
